version: "3.0"
services:
  eureka:
    image: eureka:latest
    networks:
      - e-commerce

  auth-server:
    image: user:latest
    networks:
      - e-commerce
    environment:
      - SPRINGR_DATA_MONGODB_URI=mongodb+srv://vitorgzillig:LZXNV6mqBW6WBOil@cluster.yzliv.mongodb.net/test
      - SPRING_DATA_MONGODB_DATABASE=E-Commerce
      - MANAGEMENT_SERVER_PORT=8080

  produto-service:
    image: produto:latest
    networks:
      - e-commerce
    depends_on:
      - auth-server
    environment:
      - SPRINGR_DATA_MONGODB_URI=mongodb+srv://vitorgzillig:LZXNV6mqBW6WBOil@cluster.yzliv.mongodb.net/test
      - SPRING_DATA_MONGODB_DATABASE=E-Commerce
      - MANAGEMENT_SERVER_PORT=8080

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - e-commerce
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    networks:
      - e-commerce
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      
  compra-service:
    image: compra:latest
    networks:
      - e-commerce
    depends_on:
      - auth-server
      - produto-service
      - kafka
    environment:
      - AUTH_ENDERECO=http://auth-server
      - AUTH_PORTA=8083
      - PRODUTO_ENDERECO=http://produto-service
      - PRODUTO_PORTA=8081
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=http://kafka:9092
      - SPRINGR_DATA_MONGODB_URI=mongodb+srv://vitorgzillig:LZXNV6mqBW6WBOil@cluster.yzliv.mongodb.net/test
      - SPRING_DATA_MONGODB_DATABASE=E-Commerce
      - MANAGEMENT_SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRINT_APPLICATION_NAME=compra-service

  prometheus:
    image: prom/prometheus:v2.35.0
    depends_on:
      - compra-service
      - produto-service
      - auth-server
    networks:
      - e-commerce
    restart: always
    volumes:
      - ./config:/etc/prometheus
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - e-commerce

  gateway:
    image: gateway:latest
    ports:
      - "9995:8080"
    networks:
      - e-commerce

networks:
  e-commerce:
    driver: bridge

volumes:
  prometheus-data: