version: "2.2"
services:
  auth-server:
    image: user:1.0
    ports:
      - "8083:8083"
    networks:
      - e-commerce
    environment:
      - SPRINGR_DATA_MONGODB_URI=mongodb+srv://vitorgzillig:LZXNV6mqBW6WBOil@cluster.yzliv.mongodb.net/test
      - SPRING_DATA_MONGODB_DATABASE=E-Commerce

  produto-service:
    image: produto:1.1
    ports:
      - "8081:8081"
    networks:
      - e-commerce
    depends_on:
      - auth-server
    environment:
      - SPRINGR_DATA_MONGODB_URI=mongodb+srv://vitorgzillig:LZXNV6mqBW6WBOil@cluster.yzliv.mongodb.net/test
      - SPRING_DATA_MONGODB_DATABASE=E-Commerce

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - e-commerce
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    networks:
      - e-commerce
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      
  compra-service:
    image: compra:1.1
    ports:
      - "8082:8082"
    networks:
      - e-commerce
    depends_on:
      - auth-server
      - produto-service
      - kafka
    environment:
      - AUTH_ENDERECO=http://auth-server
      - AUTH_PORTA=8083
      - PRODUTO_ENDERECO=http://produto-service
      - PRODUTO_PORTA=8081
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=http://kafka:9092
      - SPRINGR_DATA_MONGODB_URI=mongodb+srv://vitorgzillig:LZXNV6mqBW6WBOil@cluster.yzliv.mongodb.net/test
      - SPRING_DATA_MONGODB_DATABASE=E-Commerce

networks:
  e-commerce:
    driver: bridge