server:
  port: 9995

management:
  port: 9995
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PRODUTO-SERVICE
          uri: lb://PRODUTO-SERVICE
          predicates:
            - Path=/produto/**
          filters:
            - RewritePath=/produto/(?<path>.*), /$\{path}

        - id: COMPRA-SERVICE
          uri: lb://COMPRA-SERVICE
          predicates:
            - Path=/compra/**
          filters:
            - RewritePath=/compra/(?<path>.*), /$\{path}

  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8089/auth/realms/SpringBootKeycloak
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            client-id: login-app
            client-secret: 511952d8-179c-4869-8661-e8d4352f97fb
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
