# Configurações globais
global:
  scrape_interval: 15s # Vai buscar(scrap) as métricas a cada 15s por padrão

# Regras que quando atingidas geram alertas
rule_files:
#  - first.rules

# Lista de serviços para monitorar
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'compra-service'
    metrics_path: '/actuator/prometheus' # Como obter as métricas
    scrape_interval: 5s
    static_configs:
      - targets: [ 'compra-service:8080' ]

  - job_name: 'produto-service'
    metrics_path: '/actuator/prometheus' # Como obter as métricas
    scrape_interval: 5s
    static_configs:
      - targets: [ 'produto-service:8080' ]

  - job_name: 'auth-server'
    metrics_path: '/actuator/prometheus' # Como obter as métricas
    scrape_interval: 5s
    static_configs:
      - targets: [ 'auth-server:8080' ]